apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:17BaVh2mq+s=,iv:KzUKTTL/NvjRxiDnez1HmbsPH22g7A+sgD7CsRu6Dkw=,tag:XxdPYIEztMWgwqMDsETGmw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:q5e2q0tah+dn5TCO,iv:d7bXs9KeCR8C1D8OWQM9hQf3UGODLZASBAs3SLl2rDw=,tag:ng94qj41JtCgdqy4UhVvmg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1mvaxkv4tuwls92lnku23awehjhntlppchyxtylfdxytyrm4e8y4q6629hp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa1hhZmhVRFdYbHN0Z0pU
            eVhnK0VRNjIwSklvZjlqNDB5V0I0b0Y2YUVjCktWb2lwSU0wZ0E5bzl1eTNtRkVP
            NEFHREVKZXhUSE1ySXdpaW5ERkk2MTAKLS0tIFA1eVZucXFJOFoyV3FicUVmK3dI
            MWEyNDRRYVpseUFBbVE4b3ZiV3FNQnMKgX6TRl3nOG7HbMlxVSMb23JJoLJFf7Rm
            z5Wf/FtzripE4ypfx7C8chRNp1qN0d1tmEfsvCQ1E4jDzG+f+tqJ0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T07:27:15Z"
    mac: ENC[AES256_GCM,data:ATzrT7mixhGtbTtRDJ0ryQgjAfBNjD+rpDtTN70CKWsS3PPXBs2qMdon0Kn7jog7YHhTtLA9rIJa+CbM4TppIV1Rkj4dh2cEfdMDPcQXyqwqw7Zh+5Nibq4sTZOU1K4iveSY0K4N2DIzfboaf9aUx1gsfIe7OqYwcEYBLhepw5Q=,iv:x1kqh4c1q4NIYu0GK6ZmCo86/jKpg+iceMaNCQ3DLmI=,tag:5ywNfIbuLhRRdZ9CJke6BQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
