apiVersion: v1
kind: Secret
metadata:
    name: bookstack-secret
stringData:
    APP_KEY: ENC[AES256_GCM,data:xW8iX5czPGadc1TenUGfafdLQH9kOj5F6Kv+/O0lcH4pyxuvV6RgG13QeU6VkrUoE+1W,iv:eaBSk3g+CFycKLdl6ds1iE36pKDZY7DL2V39Zok8CPc=,tag:P7hwn52Bnm6HRgZKs6+0KQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:ieLkKy5c/mt3Sw==,iv:eaH0KoBYBCdvx/oblcqrUdVryVVoZFQwskB/+D53Bts=,tag:8QZi1wmIqfUM6q6zqhcNmg==,type:str]
sops:
    age:
        - recipient: age1khss8e3tj2u794n4gx9rs833gafuflmrpmg3mm6e0hwy2q8k7d3qw6qcsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRay9MT3dhUmtUYk5vUDBZ
            Rjc2OFYxQmo5NTNSeXFUaUlYdC9oaUE4QVY0CkhqZWVhMXhUZEI5a0FPM3d4ZWtG
            Ujl0bVU2NVdFcEw0VGJzNXl0YVlNOGMKLS0tIDVKcGp4c3JobzhpeXJUdFFBWTly
            ZVdjdlFNcVU5Qm9xZkVkOTZIS2xqN00KZ3YVmLbBYzct3fagLqHfQ3jocbRXr7YK
            GSizmYBiBq68c7opDKhBmGaz69UsJI/B0aXf5h+N46WKu22Uud3cFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:21:18Z"
    mac: ENC[AES256_GCM,data:C/sbXqA7duTGTi1XI8L2Uqly3UGdxJOxIl65/rOz3gDcmz67enI+wAo3TdC6z2ytiuGIoCRMbXb6B1PGIJ+FtxBoWYJJRTJC40VAXBzX6Rr/0h3z554KQdBXzwP8vDkPg/C4wMhbQMZ6JSW0V1guIh/T6515ic87So/m+sBylXI=,iv:pad8ipPx0N501Q+6+qIKuGA2vILyl53JU8Q+ccBw5A0=,tag:mXyQ3H2UafgTbpISoGjz8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
