apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    credentials.json: ENC[AES256_GCM,data:qEP5C8kKsvwxGlnqEP6N9NSh4imGNdXH73uFH3dX1rvOQG7xCmIqRYJ91GGy5rF36i17DsDLkXlwz9r7g+VfT5HVKdZAgS3G5ddqcU+U8kJiKjrqeZQKhY06D/bZi3T1qbGmpyhVvC8nmeDvK5OiDlXt6/kSqHXO48lihbYOEvOCpdgvJC+H3mWM2wwBhOtBiCNcY1evf/E79nzgxslGLAseyVJFcShYjilpfQCzkoPB3/Kwyw==,iv:YL9b0Kly1KMNNcs1zIq4ec97TkPGovprbwrsV5QhWkY=,tag:Iumvn7+yOrEZdIGYqsJVdg==,type:str]
sops:
    age:
        - recipient: age1khss8e3tj2u794n4gx9rs833gafuflmrpmg3mm6e0hwy2q8k7d3qw6qcsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjejlIQUtFdlhUSWI1dk1M
            dllEMkFHdnNvZm5LaW1CTmxZd0tUNmJMYkNVCkw1VGhGUGhWempac0JvT0hrL0V4
            TEZrdDFZV0JlTVAvQzBQeGFQN1dIOEEKLS0tIG0xL3B5VmpUMnNESEZYaDNmcWhQ
            V1RpVUxlRnAzRlhKREJ2RDhmZmhvOUkKv1fPbLuH+quQzCs8GhfN5fxFuu3f90vT
            omwwSU/aDGm6pPnI5eQbDcVx8uR9Ue3VUrAPxD053Z7hANUZVTiKhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:57:45Z"
    mac: ENC[AES256_GCM,data:pbM5t7K6y4x9cAZq+gi8gc6QVPUJCXEekF9Lie7HZJsT+argM/YGYjQeua9m+Z+2rBgTeiuZ77dlzW5hU2XTy1x6Sxcie620ElBmSxHoXNmpzKwvmCd7COjmeBDak6yqDSbIeB9/BynMLiXqofIcN9mgx/bhvWBJKNb5RJQbUZQ=,iv:E8Y5DAPW03n5eUgpx0I4akFI98aZgg7/rfv3ETacFFQ=,tag:wj3g4eR++uoQD97RV/BWTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
