apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    credentials.json: ENC[AES256_GCM,data:ccfJqp/BfXe4xNGmFLo8CJSK9AnpYyzCJuOuFZS5rOJSJtSrw+LX3IqF4AP9w3Irptp0+GCioAyuI2VazpxloMOKeLRim5YbqGwHCAFXSsaR0Qw+324PcOHcvQhP7K1DEj1v9K7Gd9pIrKAFQ9c27DR5iHAdcKiiexe4ISO49Xveg0qkDI1c04iAbG2sSh24o7yGKipl6nIZezR7kT7pxZOiH0IALkbooozlXoqF3Y/yUXlz5w==,iv:rsdDmz04p7bs5VOuBRPkvk9D9w30aRDle3VQiSFZkZA=,tag:pmmMbhM/W4rTcWWvdG/Txw==,type:str]
sops:
    age:
        - recipient: age1khss8e3tj2u794n4gx9rs833gafuflmrpmg3mm6e0hwy2q8k7d3qw6qcsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzakZ0KzVGa1RWTlhuMnFR
            OFM3cHRNcUhsbCtiRXZaTmpUU1M0dGNyRVRBCm81N0lseHUybUNrWE1mdlR5VmM1
            Z3FIT2d4U2x4b1NNL0pIMFVYQjIwT0UKLS0tIFl4cnBuT3ZOWTV5Y0dNcGdWQUN3
            RnJ3bEJGSTVpZTRuU0tKcHozRld6YWsKVoYp/EO1EM8niDdJ+ioPVDq/SvtAKIaJ
            ArBjk6X6Lv1r2z1Lbus4QzObxvR/bNEQEtJC3QFItbeb+dphD9UVwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:49:11Z"
    mac: ENC[AES256_GCM,data:olbg/1FlTnSE9hX7RVrXY1ETCUe4Mfs0JvMGTutQ5A7192YOlI/tkc6H1ptAjhyBb0ztnZRluXdVFgCIYf0jvjniLxP5klbREXvKahR1zY1Rkt7gvr3/bQIxcmwP85NbdGvvGOpiUtioc3qK9nvaH41bCVDp8ff8RCYx+O3CheI=,iv:20G8DGhCBPXenmTritQcdDRFaFelSyQlec6m0aEMb5g=,tag:CJb6fKH2xkiy3VnafDamCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
