apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    credentials.json: ENC[AES256_GCM,data:/SdKGJ5j4FTia434SCHtVWxps4Y3dBganHIfa7hCi912LXXmPWXRor3YQpPsh3IWJ5tiLEmNVJ1Gi8O9AOjYjKAImdxDMoL90hOX6qVItdDHPL7EU06TFBy8bajJFvAuBScMJlGTGRtZJpsqr0mt0E3nqASz2cD4E0vQKcmdXfQ1riRY9UUagN8bBvVOOLEp15e9a+vmpH3pl1OS8w8eFSTWwiYwgFKn2CAH+hySBoA+asoiIA==,iv:4sXBeSEsVvZljC7Uk13eNPx9ujR/WyRFOa084B0NBv4=,tag:/M9rv4lNncf1569TlKHLrw==,type:str]
sops:
    age:
        - recipient: age1khss8e3tj2u794n4gx9rs833gafuflmrpmg3mm6e0hwy2q8k7d3qw6qcsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MGdUbGxodUtxSlRxQkNo
            L3Q5MmJNTXVhd1didkNpbE9iV2dUK2w3VVdRCnhqdk9xb20ycUZjcFJYTEs0N0ky
            VndsL2g5bk5oMUpjenBRYm9vTGFBQVkKLS0tIDRCVzJ1VVJIQk5jYUdkTXR0S21z
            WjJmRWdEQVorM2ZGQ1hWZE5pMnJPc00KOcvpb7BdW8UbUsCjIVxg8ecCCOwX9gmZ
            1hjAGnzzWI2vQIdIixDswYS5o7bkM9Zy7U5zCEy+F2sZDZfciWQUHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:21:19Z"
    mac: ENC[AES256_GCM,data:hG+oM4O44cAqOP4XcyOsOoUW7qXcxTFV5ZbGH1+NMq6gYlJ7uB1eVLPvuW5aG4pG+1GklNcJ/aQLDn5szEFJxHplNAatOl1FtrjEDHxC1yVreGgnAjNLKhLOC3bdXFZ8s/+xDt6naXYCAjrAmChK6QTUMISdzCAGQsjIjzMMeDI=,iv:crWbWveNJszr8VBblC+OkV0oF7J1ZSVkqQExIRTT+c4=,tag:co2zsT44X7I4WrqupIeOEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
