apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookstack
resources:
  - ../../base/bookstack
  - mariadb-secret.yaml
  - bookstack-secret.yaml
  - cloudflare-tunnel-secret.yaml
