apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:ZdwSSJLFEJGpf4T0GxMxC/eVMEMeZQ==,iv:LhAQlHKhFVxl0cMyJHYmWiIiNP0cvZrJ2hG2zi1naXM=,tag:Wb7nKEhIiYTcX32h6VURfw==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:UUbXqOuCwHBM,iv:38tq10axleu3dZNLXvTt5PTSjBRGNOoJVcs0gGeiluQ=,tag:rotbV2cs2om8Wg480bT1qA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:lwU9yb1BDpo+,iv:H2eMpL4N7lHHZhHDm793/HpNXvCLClB5xHh5l7B3JNw=,tag:sRpCYHlpSY0liHN7ij7IXA==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:3jvH93lB4aVd7w==,iv:266buCvdmIwrN+MCUovCbrv32BWzfyIOMJuJxpZz9D0=,tag:9ygUU4q0GQow0JcWEeg6YQ==,type:str]
sops:
    age:
        - recipient: age1khss8e3tj2u794n4gx9rs833gafuflmrpmg3mm6e0hwy2q8k7d3qw6qcsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TThZMXV5VGs1S0N2VmNI
            WVJ4ZlhvYm1QVFFENnNoM3JMRENTRUVCOERVCldFMFJVYThOUFZZd0ptdTl3cXox
            RTZuNXVZS1oxbWo2Nm42MmpFTXljZU0KLS0tIGdCbDVYZDhWV1BNdGRGcWRXeTBV
            VlIyV0FUMzZwRE0vSzY1eExhZTdjWXMKtSOuLkrdI3xgYpS0mNN4a4TtfPcVLG1v
            MxIiT44Eu2QJcNGI9iUyJZDSIQ3cUG5514/jflYvON+VWPJrMy5jYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T18:21:18Z"
    mac: ENC[AES256_GCM,data:ryqbAj/U+He+Rj81+CbgeKL4CshXyjx/0IGV6B/GVxbnoOVNgyaVTEGGpEqyavksPZ1k614FJF188eOyL6ljYItOPq4F9x7kZ/tffBU6REpT6LqW1f7wHLt4iqIg7VDt7rZ/44plQIa45E8f5boV6B0WkMMADcuRckbpIt2ZB0Y=,iv:2z/q/Nwb7Lw0itcVWvVgnu6WgJhI9KGMX7VYAC5+lPM=,tag:NHKRsWyTdfpIbOZWMnhbig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
