apiVersion: v1
kind: Secret
metadata:
    name: renovate-secret
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:QJCw83NS8Iv3s02HBmp0J2E8cT30otDADXsc7b4NI2MS+WQUIHVp3ZIh3yjmClDjc4zbgOhGhQArEpf+5gK9340XOCBZsSMCk7A/WQjkCH87o6Fd9Pavi5Y2jZO+,iv:NC/RA4zOzngzMF/eBv/U5Opc+TCiLb5ZSF0WiHT+/5M=,tag:sL0/RgSAkubQqqpuImnOhg==,type:str]
sops:
    age:
        - recipient: age1khss8e3tj2u794n4gx9rs833gafuflmrpmg3mm6e0hwy2q8k7d3qw6qcsz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ejFOK3pVODhtUCtYWUxD
            OWtlMnNuQy8xdFR6K0hic2pVcjVYUmZWRUFVCnBNeUxta3BsMUtaME92eWxSK29z
            cE8zTjU4cEF1UUhNS0p6K0F5bWl4dlEKLS0tIHN0QjZkbnlqS3EydWM3VU9wOXhv
            QTJxVmNZak1GTFY5OHRxcEMydW0wa0EK5cg5idrpphJDLopwa6pKxbb7uECG7kao
            E3+KztZsqyrwQjZ79uc8Kp5XwnCuCr12jXgkgJRGVCftcj0JFCmr0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T20:01:30Z"
    mac: ENC[AES256_GCM,data:ZMJam2aiRm7mKJ0TZm3Fj875pBycjcUXqbGOr58n8JBsAen3g/w35BYTc/AZxLTxxRkfGAu3evcYVY+TlfPsOZofLah0nqrV/kiiGZqJFvwTQ53rllJcDL1pcGe70hSTWyJXGP0Idi0Po3uMusCsaL5p5K6VAH/4IuWVXgmnIkg=,iv:y7Bv5daCMnzciRDRZAmuKYpEqzF14wTLsw/LLRFo2VU=,tag:srBkc8EiR+je9OxhF9FRtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
