apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: |
    tunnel: bb7ebd4c-8707-44e9-a0aa-bd572ab2ca99
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: bookstack.kubelaba.com
        service: http://bookstack:80
      - service: http_status:404
