apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistentvolumeclaims.yaml
  - bookstack-configmap.yaml
  - cloudflare-tunnel-configmap.yaml
  - mariadb.yaml
  - bookstack.yaml
  - cloudflare-tunnel.yaml
